// Creates the per-developer secrets that are deliberately kept out of git, so
// a fresh clone can run `serverpod start`, `dart test` and the Docker backend.
//
//   cd hackathon_serverpod_server
//   dart run tool/init_local_secrets.dart
//
// Written in Dart rather than shell so it runs the same on Linux, macOS and
// Windows with nothing but the toolchain the project already needs.
//
// It never overwrites an existing file. The embedded PostgreSQL under
// `.serverpod/` is initialised with the database password on its first start,
// so replacing that password later would lock you out of your local database.
import 'dart:convert';
import 'dart:io';
import 'dart:math';

final _random = Random.secure();

/// 24 random bytes as URL-safe base64: 32 characters, no quoting needed.
String _secret() =>
    base64Url.encode(List.generate(24, (_) => _random.nextInt(256)));

void main() {
  _writeIfMissing('config/passwords.yaml', _passwordsYaml);
  _writeIfMissing('.env', _dotEnv);
}

void _writeIfMissing(String pathInServer, String Function() content) {
  final file = File(Platform.script.resolve('../$pathInServer').toFilePath());
  if (file.existsSync()) {
    stdout.writeln('kept     $pathInServer (already exists)');
    return;
  }
  file.writeAsStringSync(content());
  stdout.writeln('created  $pathInServer');
}

/// Mirrors the file `serverpod create` generates, for the two run modes used
/// locally. Staging is the Docker backend, which reads `.env` instead, and
/// production secrets live in Serverpod Cloud.
String _passwordsYaml() =>
    '''
# Local secrets, generated by tool/init_local_secrets.dart. Not under version
# control: every developer has their own.

development:
  database: '${_secret()}'
  redis: '${_secret()}'
  serviceSecret: '${_secret()}'
  emailSecretHashPepper: '${_secret()}'
  jwtHmacSha512PrivateKey: '${_secret()}'
  jwtRefreshTokenHashPepper: '${_secret()}'

test:
  database: '${_secret()}'
  redis: '${_secret()}'
  emailSecretHashPepper: '${_secret()}'
  jwtHmacSha512PrivateKey: '${_secret()}'
  jwtRefreshTokenHashPepper: '${_secret()}'
''';

/// The variables docker-compose.yaml passes to the `server` service.
String _dotEnv() =>
    '''
SERVERPOD_SERVICE_SECRET=${_secret()}
SERVERPOD_PASSWORD_emailSecretHashPepper=${_secret()}
SERVERPOD_PASSWORD_jwtHmacSha512PrivateKey=${_secret()}
SERVERPOD_PASSWORD_jwtRefreshTokenHashPepper=${_secret()}
''';
