name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '4.0.0'
      SERVERPOD_PASSWORD_database: 'C8cw2Okb3HjBc36Y_hOtF5HOvy0qWQjo'
      SERVERPOD_PASSWORD_redis: 'gigs8RMMdIVrlGDiZVvgEestnZB1CSs2'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'

      - name: Start containers
        working-directory: hackathon_serverpod_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart install serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: hackathon_serverpod_server
        run: serverpod generate

      - name: Run tests
        working-directory: hackathon_serverpod_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: hackathon_serverpod_server
        run: docker compose down -v
