import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// The app's five UI sounds. Each one means one thing, everywhere — see
/// docs/DESIGN.md for when each is used. The files live in assets/sounds/ and
/// are generated by tool/generate_ui_sounds.dart.
enum AppSound {
  /// A bubbly pop. Pressing a primary or secondary button.
  tap,

  /// A rising chime. Something the user did went through: a group created, a
  /// vote cast, a task proposed.
  success,

  /// The coin "bling". Coins come in.
  coin,

  /// A small descending "womp". Coins go out as a fine.
  fine,

  /// A soft "bonk". Something failed.
  error,
}

/// Plays [AppSound]s. Each sound has its own pool of pre-loaded players, so a
/// fast second tap does not cut the first one off or wait for a file load.
class UiSounds {
  UiSounds._(this._pools);

  /// Plays nothing. The default, so tests and any platform where audio fails
  /// to load keep working exactly as before.
  UiSounds.silent() : _pools = const {};

  final Map<AppSound, AudioPool> _pools;

  /// Off switch for the whole app. Not persisted yet — a toggle in settings is
  /// the natural home for it.
  bool muted = false;

  /// Loads every sound. Never throws: if a sound will not load, the app gets a
  /// silent player instead of an error, because a missing "pop" must never stop
  /// someone signing in.
  static Future<UiSounds> load() async {
    try {
      final pools = <AppSound, AudioPool>{
        for (final sound in AppSound.values)
          sound: await AudioPool.createFromAsset(
            path: 'sounds/${sound.name}.wav',
            maxPlayers: 3,
          ),
      };
      return UiSounds._(pools);
    } catch (error) {
      debugPrint('UI sounds disabled: $error');
      return UiSounds.silent();
    }
  }

  /// Fire and forget: a sound that fails to play is dropped, never reported.
  void play(AppSound sound) {
    if (muted) return;
    _pools[sound]?.start(volume: .7).ignore();
  }
}

/// The app-wide player. Silent unless `main` overrides it with a loaded one.
final uiSoundsProvider = Provider<UiSounds>((ref) => UiSounds.silent());
